#!/usr/bin/env python3
"""Create or refresh agent workspaces (agents/<name>/) and the shared team roster.

  setup_agent.py create NAME TOOL ROLE INSTRUCTION [MODEL] [--lead]
  setup_agent.py refresh [NAME]     rebuild config files from agent.json (all agents if no name)
  setup_agent.py team               regenerate .agent_sync/TEAM.md
TOOL: claude | opencode | qwen | codex
"""
import glob, json, os, sys
import config

PROVIDERS = {"claude": "Claude Code", "opencode": "OpenCode", "qwen": "Qwen Code", "codex": "Codex"}


def dump(path, data):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w") as f:
        if isinstance(data, str):
            f.write(data)
        else:
            json.dump(data, f, indent=2); f.write("\n")


def agents_dir(cfg):
    return os.path.join(cfg["root"], "agents")


def all_agents(cfg):
    out = []
    for f in sorted(glob.glob(os.path.join(agents_dir(cfg), "*", "agent.json"))):
        with open(f) as fh:
            out.append(json.load(fh))
    return out


def write_team(cfg):
    lead = cfg["lead"]
    rows = all_agents(cfg)
    lines = [
        "# Team roster",
        "_Generated by .agent_sync/setup_agent.py — do not edit by hand._",
        "",
        f"- **Human:** `@{cfg['human']}` (final say on everything)",
        f"- **Lead:** " + (f"`@{lead}`" if lead else f"none — {cfg['human']} assigns work directly"),
        f"- **Room:** `{cfg['room']}` on the TropaAI chat at {cfg['server']} (monitor: open it in a browser)",
        f"- **Project docs/specs:** `{cfg['docs_path']}`",
        "",
        "| Agent | Lead | Runs in | Model | Role |",
        "|---|---|---|---|---|",
    ]
    for a in rows:
        lines.append(f"| `@{a['name']}` | {'★' if a['name'] == lead else ''} | {a['provider']} | "
                     f"{a.get('model') or 'CLI default'} | {a.get('role', '')} |")
    if not rows:
        lines.append("| — | | | | |")
    dump(os.path.join(config.HERE, "TEAM.md"), "\n".join(lines) + "\n")


def write_agent(cfg, a):
    name, tool = a["name"], a["tool"]
    ws = os.path.join(agents_dir(cfg), name)
    rules = os.path.join(cfg["root"], "AGENTS.md")
    team = os.path.join(config.HERE, "TEAM.md")
    mcp_url = f"{cfg['server']}/mcp?agent={name}&project={cfg['project']}"
    is_lead = cfg["lead"] == name
    lead_block = f"""
# You are the team lead
- When `@{cfg['human']}` posts without naming an agent, the message comes to you.
- Break the work down and assign each piece by mentioning the agent who owns it (`@name ...`). A mention is an assignment.
- Track progress in the room, unblock agents, and report results or decisions needed back to `@{cfg['human']}`.
""" if is_lead else ""

    dump(os.path.join(ws, "AGENT.md"), f"""# Your identity
- **Agent name:** `{name}` — always pass `agent: "{name}"` to the tropa tools.
- **Role:** {a.get('role', '')}
- **Runs in:** {PROVIDERS[tool]}{f" · model {a['model']}" if a.get('model') else ""}
- **Project room:** `{cfg['room']}`
- **Project folder:** `{cfg['root']}` (docs and specs in `{cfg['docs_path']}`)
- **Where to write:** all project files go under `{cfg['root']}` — use absolute paths. Your own folder `{ws}` only holds your config; never put project code there.
{lead_block}
# Initial instruction
{a.get('instruction', '')}

# Team rules
Follow `{rules}` (AGENTS.md) and see the roster in `{team}` (TEAM.md). Read them at startup if they are not already in your context.

# When a prompt starting with `[tropa]` arrives
It was typed by the room watcher, not by {cfg['human']}. Read the room, decide per AGENTS.md whether you need to act, and stay silent if not.
""")

    if tool == "claude":
        dump(os.path.join(ws, "CLAUDE.md"), f"@{rules}\n@{team}\n@AGENT.md\n")
        dump(os.path.join(ws, ".mcp.json"), {"mcpServers": {"tropa": {"type": "http", "url": mcp_url}}})
        dump(os.path.join(ws, ".claude", "settings.json"),
             {"enableAllProjectMcpServers": True,
              "permissions": {"allow": ["mcp__tropa", f"Edit(/{cfg['root']}/**)"] + list(cfg.get("claude_allow", [])),
                              "additionalDirectories": [cfg["root"]]}})
    elif tool == "opencode":
        # OpenCode runs from the project folder with OPENCODE_CONFIG pointing here,
        # so it picks up the root AGENTS.md itself and can edit project files.
        dump(os.path.join(ws, "opencode.json"),
             {"$schema": "https://opencode.ai/config.json",
              "instructions": [team, os.path.join(ws, "AGENT.md")],
              "mcp": {"tropa": {"type": "remote", "url": mcp_url, "enabled": True}}})
    elif tool == "qwen":
        dump(os.path.join(ws, "QWEN.md"), f"@{rules}\n@{team}\n@AGENT.md\n")
        dump(os.path.join(ws, ".qwen", "settings.json"),
             {"mcpServers": {"tropa": {"httpUrl": mcp_url, "trust": True}}})
    return ws


def main():
    cfg = config.load()
    args = sys.argv[1:]
    if not args:
        sys.exit(__doc__)
    cmd = args.pop(0)
    if cmd == "create":
        lead = "--lead" in args
        args = [x for x in args if x != "--lead"]
        if len(args) < 4 or args[1] not in PROVIDERS:
            sys.exit(__doc__)
        name, tool, role, instruction = args[:4]
        model = args[4] if len(args) > 4 else ""
        a = {"name": name, "tool": tool, "provider": PROVIDERS[tool], "model": model,
             "role": role, "instruction": instruction}
        dump(os.path.join(agents_dir(cfg), name, "agent.json"), a)
        if lead:
            config.save_key("lead", name)
            cfg = config.load()
        write_team(cfg)
        print(write_agent(cfg, a))
    elif cmd == "refresh":
        write_team(cfg)
        for a in all_agents(cfg):
            if not args or a["name"] in args:
                write_agent(cfg, a)
    elif cmd == "team":
        write_team(cfg)
    else:
        sys.exit(__doc__)


if __name__ == "__main__":
    main()
